// Command ucdgen generates vt/grapheme_tables.go from the Unicode Character
// Database: the grapheme cluster break property, Extended_Pictographic,
// Emoji, Indic_Conjunct_Break and the cell width implied by East_Asian_Width,
// packed into one value per run of code points.
//
//	go generate ./vt
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

const version = "17.0.0"

// Packed property layout; mirrored by the constants in vt/grapheme.go.
const (
	gcbOther = iota
	gcbCR
	gcbLF
	gcbControl
	gcbExtend
	gcbZWJ
	gcbRI
	gcbPrepend
	gcbSpacingMark
	gcbL
	gcbV
	gcbT
	gcbLV
	gcbLVT
)

const (
	bitExtPict    = 1 << 4
	incbShift     = 5
	bitEmoji      = 1 << 7
	widthShift    = 8
	incbConsonant = 1
	incbExtend    = 2
	incbLinker    = 3
)

var gcbNames = map[string]uint16{
	"CR": gcbCR, "LF": gcbLF, "Control": gcbControl, "Extend": gcbExtend,
	"ZWJ": gcbZWJ, "Regional_Indicator": gcbRI, "Prepend": gcbPrepend,
	"SpacingMark": gcbSpacingMark, "L": gcbL, "V": gcbV, "T": gcbT,
	"LV": gcbLV, "LVT": gcbLVT,
}

const maxRune = 0x10FFFF

func main() {
	out := flag.String("o", "grapheme_tables.go", "output file")
	cache := flag.String("ucd", "", "directory holding the UCD files (default: download)")
	flag.Parse()

	gcb := make([]uint16, maxRune+1)
	extPict := make([]bool, maxRune+1)
	emoji := make([]bool, maxRune+1)
	emojiPres := make([]bool, maxRune+1)
	incb := make([]uint16, maxRune+1)
	wide := make([]bool, maxRune+1)

	for _, r := range [][2]rune{{0x3400, 0x4DBF}, {0x4E00, 0x9FFF}, {0xF900, 0xFAFF}, {0x20000, 0x2FFFD}, {0x30000, 0x3FFFD}} {
		for c := r[0]; c <= r[1]; c++ {
			wide[c] = true
		}
	}

	read(*cache, "auxiliary/GraphemeBreakProperty.txt", func(lo, hi rune, f []string) {
		v, ok := gcbNames[f[0]]
		if !ok {
			log.Fatalf("unknown grapheme break property %q", f[0])
		}
		for c := lo; c <= hi; c++ {
			gcb[c] = v
		}
	})
	read(*cache, "emoji/emoji-data.txt", func(lo, hi rune, f []string) {
		var dst []bool
		switch f[0] {
		case "Extended_Pictographic":
			dst = extPict
		case "Emoji":
			dst = emoji
		case "Emoji_Presentation":
			dst = emojiPres
		default:
			return
		}
		for c := lo; c <= hi; c++ {
			dst[c] = true
		}
	})
	read(*cache, "DerivedCoreProperties.txt", func(lo, hi rune, f []string) {
		if f[0] != "InCB" || len(f) < 2 {
			return
		}
		v := map[string]uint16{"Consonant": incbConsonant, "Extend": incbExtend, "Linker": incbLinker}[f[1]]
		for c := lo; c <= hi; c++ {
			incb[c] = v
		}
	})
	read(*cache, "EastAsianWidth.txt", func(lo, hi rune, f []string) {
		w := f[0] == "W" || f[0] == "F"
		for c := lo; c <= hi; c++ {
			wide[c] = w
		}
	})

	packed := make([]uint16, maxRune+1)
	for c := 0; c <= maxRune; c++ {
		v := gcb[c]
		if extPict[c] {
			v |= bitExtPict
		}
		if emoji[c] {
			v |= bitEmoji
		}
		v |= incb[c] << incbShift
		v |= cellWidth(rune(c), gcb[c], wide[c] || emojiPres[c]) << widthShift
		packed[c] = v
	}

	var starts []int
	var props []uint16
	prev := ^uint16(0) // no packed value, so the first code point starts a run
	for c, v := range packed {
		if v != prev {
			starts = append(starts, c)
			props = append(props, v)
			prev = v
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by vt/internal/ucdgen from Unicode %s; DO NOT EDIT.\n\npackage vt\n\n", version)
	fmt.Fprintf(&b, "// UnicodeVersion is the Unicode version of the grapheme tables.\nconst UnicodeVersion = %q\n\n", version)
	fmt.Fprintf(&b, "// graphemeStarts[i] is the first code point of a run that has the packed\n// properties graphemeProps[i].\nvar graphemeStarts = [...]uint32{")
	for i, s := range starts {
		if i%10 == 0 {
			b.WriteString("\n\t")
		} else {
			b.WriteString(" ")
		}
		fmt.Fprintf(&b, "0x%X,", s)
	}
	b.WriteString("\n}\n\nvar graphemeProps = [...]uint16{")
	for i, p := range props {
		if i%12 == 0 {
			b.WriteString("\n\t")
		} else {
			b.WriteString(" ")
		}
		fmt.Fprintf(&b, "0x%03X,", p)
	}
	b.WriteString("\n}\n")
	if err := os.WriteFile(*out, []byte(b.String()), 0o600); err != nil {
		log.Fatal(err)
	}
	log.Printf("%d runs", len(starts))
}

// cellWidth is the width of a code point standing alone at the start of a
// grapheme cluster.
func cellWidth(c rune, gcb uint16, wide bool) uint16 {
	switch {
	case gcb == gcbCR || gcb == gcbLF || gcb == gcbControl:
		return 0
	case c >= 0x1F3FB && c <= 0x1F3FF: // emoji modifiers are Extend but draw wide alone
		return 2
	case gcb == gcbExtend || gcb == gcbZWJ || gcb == gcbV || gcb == gcbT:
		return 0
	case wide:
		return 2
	}
	return 1
}

// read calls fn for each data line of a UCD file with its code point range
// and its remaining semicolon-separated fields.
func read(cache, name string, fn func(lo, hi rune, fields []string)) {
	var r io.Reader
	if cache != "" {
		f, err := os.Open(filepath.Join(cache, filepath.Base(name))) // #nosec G304 -- a path the developer passes
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close() //nolint:errcheck
		r = f
	} else {
		url := "https://www.unicode.org/Public/" + version + "/ucd/" + name
		client := &http.Client{Timeout: time.Minute}
		resp, err := client.Get(url) // #nosec G107 -- a fixed unicode.org URL
		if err != nil {
			log.Fatal(err)
		}
		defer resp.Body.Close() //nolint:errcheck
		if resp.StatusCode != http.StatusOK {
			log.Fatalf("%s: %s", url, resp.Status)
		}
		r = resp.Body
	}
	sc := bufio.NewScanner(r)
	for sc.Scan() {
		line, _, _ := strings.Cut(sc.Text(), "#")
		if strings.TrimSpace(line) == "" {
			continue
		}
		parts := strings.Split(line, ";")
		for i := range parts {
			parts[i] = strings.TrimSpace(parts[i])
		}
		lo, hi := parseRange(parts[0])
		fn(lo, hi, parts[1:])
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
}

func parseRange(s string) (lo, hi rune) {
	a, b, isRange := strings.Cut(s, "..")
	l, err := strconv.ParseUint(a, 16, 32)
	if err != nil {
		log.Fatalf("bad code point %q", s)
	}
	h := l
	if isRange {
		if h, err = strconv.ParseUint(b, 16, 32); err != nil {
			log.Fatalf("bad code point %q", s)
		}
	}
	return rune(l), rune(h) // #nosec G115 -- at most 0x10FFFF
}
